name: weather
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  blurrycontainer: ^0.1.0
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  mobx_codegen: ^2.0.6
  dio: ^4.0.6
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  weather_icons: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/forecasts/day/
    - lib/assets/images/forecasts/night/

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: lib/core/fonts/WeatherIcons.ttf
